# universes.py

NIFTY_50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BPCL.NS", "BHARTIARTL.NS",
    "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS", "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LTIM.NS",
    "LT.NS", "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS", "SUNPHARMA.NS",
    "TATAMOTORS.NS", "TCS.NS", "TATASTEEL.NS", "TATACONSUM.NS", "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS"
]

NIFTY_MIDCAP_100 = [
    "AUROPHARMA.NS", "BERGEPAINT.NS", "BHEL.NS", "BOSCHLTD.NS", "CANBK.NS", "COFORGE.NS", "CONCOR.NS", "CUMMINSIND.NS", "DLF.NS", "GAIL.NS",
    "GODREJPROP.NS", "HDFCAMC.NS", "HINDCOPPER.NS", "HINDPETRO.NS", "IDFCFIRSTB.NS", "INDHOTEL.NS", "JINDALSTEL.NS", "JSWENERGY.NS", "LICHSGFIN.NS", "LUPIN.NS",
    "M&MFIN.NS", "MRF.NS", "MPHASIS.NS", "MUTHOOTFIN.NS", "NMDC.NS", "OFSS.NS", "PAGEIND.NS", "PERSISTENT.NS", "PETRONET.NS", "PFC.NS",
    "PIIND.NS", "PNB.NS", "POLYCAB.NS", "SAIL.NS", "SRF.NS", "SUNTV.NS", "TATAPOWER.NS", "TATACHEM.NS", "TATACOMM.NS", "TATAELXSI.NS",
    "TORNTPOWER.NS", "TVSMOTOR.NS", "UBL.NS", "UNIONBANK.NS", "VOLTAS.NS", "ZEEL.NS", "ZOMATO.NS", "ABB.NS", "ACC.NS", "ADANIPOWER.NS",
    "ASHOKLEY.NS", "ASTRAL.NS", "BALKRISIND.NS", "BANKBARODA.NS", "BATAINDIA.NS", "BHARATFORG.NS", "BIOCON.NS", "COLPAL.NS", "DALBHARAT.NS",
    "DEEPAKNTR.NS", "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "FORTIS.NS", "GICRE.NS", "GLAND.NS", "GLENMARK.NS", "GODREJIND.NS", "HINDZINC.NS",
    "ICICIGI.NS", "ICICIPRULI.NS", "IDBI.NS", "IDEA.NS", "IEX.NS", "IGL.NS", "INDIACEM.NS", "IRCTC.NS", "JIOFIN.NS", "JSWINFRA.NS",
    "LAURUSLABS.NS", "LODHA.NS", "LTTS.NS", "MANAPPURAM.NS", "MAXHEALTH.NS", "MOTHERSON.NS", "NAUKRI.NS", "NYKAA.NS", "OBEROIRLTY.NS",
    "PAYTM.NS", "RECLTD.NS", "SBICARD.NS", "SIEMENS.NS", "SONACOMS.NS", "STAR.NS", "SYNGENE.NS", "TATATECH.NS", "TRENT.NS", "YESBANK.NS"
]

HIGH_LIQUIDITY_SMALLCAPS = [ # A sample of highly traded small-cap stocks
    "BSE.NS", "CDSL.NS", "IRCON.NS", "RVNL.NS", "HUDCO.NS", "IRFC.NS", "NBCC.NS", "NATIONALUM.NS", "SUZLON.NS", "IDFCFIRSTB.NS",
    "RPOWER.NS", "SOUTHBANK.NS", "LLOYDSENGG.NS", "UJJIVANSFB.NS", "WELCORP.NS"
]